Issue #3323770: Add a ddev and gitpod enabled project template
drunomics/lupus-decoupled-project pull request #1
Opened 2022-11-25 14:59 UTC by StavoveiC

2022-11-29 13:45 UTC, fago requested changes

2022-11-29 13:45 UTC, fago commented on composer.json
> +        "psr/container": "^2.0.2"
can we remove this?

2022-11-29 13:45 UTC, fago commented on composer.json
> +        "drupal/core-recommended": "^10",
should be in main require, why dev?

2022-11-29 13:45 UTC, fago commented on composer.json
> +        "drupal/lupus_decoupled": "^1.0@alpha"
should be in main require, why dev?

2022-11-29 13:45 UTC, fago commented on composer.lock
> -            "name": "doctrine/annotations",
not sure, since this is a template, should we drop the lockfile so upon installation latest packages get picked?

2022-11-30 11:42 UTC, mostepaniukvm requested changes

2022-11-30 11:42 UTC, mostepaniukvm commented on .gitpod.yml
> +      ddev drush en lupus_decoupled_ce_api lupus_decoupled_cors lupus_decoupled_menu -y
tested in gitpod and these modules are enabled but not the main on  - lupus_decoupled

Can we change drush command and enable only  lupus_decoupled and let lupus_decoupled_* enable automatically

2022-12-22 16:05 UTC, fago approved these changes

2022-12-22 16:05 UTC, merged